name: Docker Image CI

on:
  push:
    tags:
    - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: ghcr.io login
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Run Buildx
      run: |
        docker buildx build \
        --pull \
        --push \
        --platform linux/amd64 \
        --tag ghcr.io/nicolaschan/3dtictactoe:${GITHUB_REF#refs/*/} \
        --tag ghcr.io/nicolaschan/3dtictactoe:latest .
